Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.define "ubuntu-python"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    sudo apt-get install -y python3 python3-pip

    sudo pip3 install psycopg2 Django
  SHELL

  config.vm.provision "file", source: "example.txt", destination: "~/example.txt"
end